# Generated by Django 5.2.14 on 2026-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCertificateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_to_send', models.DateField()),
                ('to_name', models.CharField(max_length=255)),
                ('send_to_type', models.CharField(default='recipient', max_length=50)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('from_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GiftCertificate',
        ),
    ]
